### ISSUE TITLE
Tags are not set correctly

### ISSUE THREAD

**Issue by GROwen** [dpc-sdp/bay#211]
## Describe the bug
When GitHub Actions executes the build-deploy workflow the container images should be tagged according to the expected behaviour

## To Reproduce

**Background (prerequisites)**
[Patched version of ACT](https://github.com/nektos/act/pull/2061)
Clone this branch and run `sudo make install` then point the following commands and the resulting binary i.e. `$HOME/go/src/github.com/nektos/act/dist/local/act`

**Testing workflow event files**
Execute the [build-deploy workflow](https://github.com/dpc-sdp/bay/blob/5.x/.github/workflows/build-deploy.yml)

```
workflow-dispatch.yml

{
  "inputs": null,
  "ref": "5.x",
  "repo": "dpc-sdp/bay",
  "sender": "GROwen",
  "workflow": "test-context-values"
}
```

```
pull_request.json

{
  "pull_request": {
    "head": {
      "ref": "build/DDS-1723--sample"
    },
    "base": {
      "ref": "5.x"
    },
    "merged": false
  }
}
```

## Steps to reproduce the behavior:
Execute the following commands adjusting the inputs based on the scenario

```
$HOME/go/src/github.com/nektos/act/dist/local/act workflow_dispatch -W .github/workflows/build-deploy.yml --defaultbranch "5.x" --actor "GROwen" -s GITHUB_TOKEN --var BRANCHES='["5.x"]' --var IMAGES='["ci-builder"]' --env REGISTRY=ghcr.io --container-architecture linux/amd64 --rm -P ubuntu-latest=catthehacker/ubuntu:act-latest -e .github/pull_request.json
```

You can also use the `test-context-values.yml` to check the GitHub context (ghc) that `act` computes for each run.

```
---
test-context-values.yml

name: test-context-values
run-name: Test cases for workflow triggers
on:
  pull_request:
    types:
      - closed
      - opened
      - synchronize
  schedule:
    - cron: '23 20 * * 0'
  workflow_dispatch:
jobs:
  github_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```

## Expected behavior

Scenarios
item | workflow trigger | Event | Expected tag | Notes
-- | -- | -- | -- | --
1 | pull_request | [opened](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=opened#pull_request) | `pr-86` |  
2 | pull_request | [synchronize](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request) | `pr-86` |  
3 | pull_request | [closed](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=closed#pull_request) | base branch GITHUB_REF i.e. `5.x` | Future state: delete pr tag
4 | schedule |   | Default branch GITHUB_REF i.e. `5.x` |  
5 | workflow_dispatch | [workflow_dispatch](https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_dispatch) - request specifics - [create-a-workflow-dispatch-event](https://docs.github.com/en/free-pro-team@latest/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event) |  GITHUB_REF i.e. `5.x`
